import mongoose from 'mongoose'

const savedTripSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },

    // Where this trip came from
    // "manual" = user built it themselves in My Trips
    // "ai"     = generated by the AI planner and saved
    source: {
      type: String,
      enum: ['manual', 'ai'],
      default: 'manual',
    },

    city: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'City',
    },
    citySlug: { type: String },

    // Date range (optional — user may not set dates right away)
    startDate: { type: Date },
    endDate:   { type: Date },

    // How complete the itinerary is — shown as progress bar in UI
    // 0–100, user updates this as they add more days/places
    progressPercent: {
      type: Number,
      default: 0,
      min: 0,
      max: 100,
    },

    // Only filled when source === "ai"
    params: {
      destination: { type: String },
      days:        { type: Number },
      theme:       { type: String },   // "heritage", "adventure", "food"
      budget:      { type: String },   // "budget", "mid-range", "luxury"
      groupType:   { type: String },   // "solo", "couple", "family"
    },

    // Day-by-day itinerary — works for both manual and AI trips
    itinerary: [
      {
        day:       { type: Number },
        title:     { type: String },      // e.g. "Day 1 — South Mumbai"
        narrative: { type: String },      // AI note or user note for the day
        places: [
          {
            placeId: {
              type: mongoose.Schema.Types.ObjectId,
              ref: 'Place',
            },
            name: { type: String },       // Snapshot — safe if place is deleted
            slug: { type: String },
            note: { type: String },       // Specific note for this stop
            _id: false,
          },
        ],
        _id: false,
      },
    ],

    // Raw Claude response — only set when source === "ai", hidden by default
    rawResponse: {
      type: String,
      select: false,
    },

    isPublic: { type: Boolean, default: false },
  },
  { timestamps: true }
)

savedTripSchema.index({ user: 1 })
savedTripSchema.index({ user: 1, source: 1 })
savedTripSchema.index({ citySlug: 1, isPublic: 1 })

export default mongoose.model('SavedTrip', savedTripSchema)